### ISSUE TITLE
Get the PagingState from the TypedQuery, NativeQuery, find

### ISSUE THREAD

**Issue by amorillotraxens** [doanduyhai/Achilles#219] opened 2015-07-09 08:08 UTC
It would be nice to be able to paginate thru Typed Queries (and Native, and find()...). As we don't have access to ResultSet, we cannot get the ExecutionInfo which contains the PagingState.

For example :

	RegularStatement query = QueryBuilder.select().from("mytable").limit(count);
        TypedQuery myQuery = manager.typedQuery(MyClass.class, query);
        List<MyCLass> myResult = myQuery.get();
        PagingState pagingState = myQuery.getExecutionInfo().getPagingState();

What do you think ? Is there any other way, except thru ResultSet, to get PagingState in Achilles ?

**Comment by doanduyhai** [comment] 2015-07-09 09:22
To use server-side paging, you can call `iterator()` from the `TypedQuery`:

```java
RegularStatement query = QueryBuilder.select().from("mytable").limit(count);
TypedQuery myQuery = manager.typedQuery(MyClass.class, query);
Iterator<MyClass> iter = myQuery.iterator(100); // page size = 100

while(iter.hasNext()) {
   MyClass instance = iter.next();
  ...
}
```

If you want to retrieve the PagingState, it is currently not possible because it's a brand new feature that has just been released in the last version of the Java driver, I'll need to add it to Achiles API. 

But in the meantime, you can use paging with  `iterator(fetchSize)`

**Comment by amorillotraxens** [comment] 2015-07-09 11:37
I would rather need the PaginState, as I will paginate from the client, not from the server. So I will not keep any context on the server.

**Comment by doanduyhai** [comment] 2015-07-09 14:12
Ok, in this case I'll add a new method to retrieve the results + paging state

**Closed** 2015-07-14 08:07 UTC
Labels: enhancement

**Comment by doanduyhai** [comment] 2015-07-14 13:23
Fixed in Achilles 3.2.2

**Comment by dhruv7491** [comment] 2016-10-05 10:42
can you show a server side paginated call using paging state

**Comment by doanduyhai** [comment] 2016-10-05 11:30
```java

//Page 1
Tuple2<List<ENTITY>, ExecutionInfo> page1 = manager.dsl()
     .select()
     .allColumns_FromBaseTable()
     .where()
     ...
     .withFetchSize(xxx)
     .getListWithStats();

...

ExecutionInfo stats = page1._2();

//Page2
Tuple2<List<ENTITY>, ExecutionInfo> page1 = manager.dsl()
     .select()
     .allColumns_FromBaseTable()
     .where()
     ...
     .withPagingState(stats.getPagingState())
     .withFetchSize(xxx)
     .getListWithStats();

//Etc ...
```

**Comment by dhruv7491** [comment] 2016-10-05 11:54
@Path("/{pageNumber}")
@GET
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public ResponseEntity<RestResponse<List<Offer>>> add(@HeaderParam("X-TenantId")String tenantId,@PathParam("pageNumber")int pageNumber){
	TenantContext.setCurrentTenant(tenantId);
	return RestUtils.successResponse(offerService.getListOfOffers(pageNumber));
this is my api the user will send me the page number value he wants to dispaly
i will be sending 10 records per page 

public List<Offer> getOfferList(int pageNumber) {
		return getRepositoryType().dsl()
				.select()
				.allColumns_FromBaseTable()
				.without_WHERE_Clause()
				.withFetchSize(10)
				.getListWithStats();
		
		}
how should is form a query to get 10 records for different pages

**Comment by doanduyhai** [comment] 2016-10-05 12:37
Cassandra does not work that way, you cannot just specify the **page number**. You always needs to provide the **paging state** (object or as a string).

So instead of returning a page of 10 objecst to the client, you should return a page of 10 objects **plus** the paging state. On the client side, you should keep a `Map<PageNumber, PagingState>` so that if you want to navigate directly to page n°10, you can send the corresponding paging state to Cassandra.

Furthermore, paging in Cassandra is very limited:

* to access a page `N`, you must fetch first the data of this page to get the paging state. For example, if you are reading currently page `3`, you cannot access page `7` directly because you just don't have paging state n°6. The only way to access page `7` is to load page by page until page `7`. Once you get there, just put the paging state you retrieve in the Map so that the next time you can jump directly there

* there is **no isolation** when you page through data. While going through page, data are being inserted in **real time** into Cassandra so the next time you request page `7`  you may have extra records that were not there the last time you load page `7`

**Comment by dhruv7491** [comment] 2016-10-07 11:03
can you post a sample query with paging state

**Comment by doanduyhai** [comment] 2016-10-07 11:12
```java
Tuple2<List<ENTITY>, ExecutionInfo> page2 = manager.dsl()
     .select()
     .allColumns_FromBaseTable()
     .where()
     ...
     .withPagingState(stats.getPagingState())
     .withFetchSize(xxx)
     .getListWithStats();
```

**Comment by dhruv7491** [comment] 2016-10-07 20:03
how can i move from page 2 to1

**Comment by doanduyhai** [comment] 2016-10-07 20:07
> how can i move from page 2 to1

Inject the paging state string of page 1 to the query ...

**Comment by dhruv7491** [comment] 2016-10-10 07:23
i am getting the list of row but in execution info the paging state is null
if i use the below query
Tuple2<List<ENTITY>, ExecutionInfo> page1 = manager.dsl()
     .select()
     .allColumns_FromBaseTable()
     .where()
     ...
     .withFetchSize(xxx)
     .getListWithStats();

...

ExecutionInfo stats = page1._2();

**Comment by doanduyhai** [comment] 2016-10-10 07:31
1) Which version of Achilles are you using ? There was a fix about a bug on fetchSize
2) How many rows do you have in the returned List?
3) How many rows do you have in the table ?

**Comment by dhruv7491** [comment] 2016-10-10 07:35
5.0.0
2
5

**Comment by doanduyhai** [comment] 2016-10-10 07:44
let me try to reproduce your issue

**Comment by dhruv7491** [comment] 2016-10-10 09:54
have you tried the senario

**Comment by dhruv7491** [comment] 2016-10-12 02:47
is there any update on the issue

**Comment by doanduyhai** [comment] 2016-10-15 15:31
I've set up an integration test and it works for me:

```java
  @Test
    public void should_query_with_paging_state() throws Exception {
        //Given
        final Map<String, Object> values = new HashMap<>();
        final long id = RandomUtils.nextLong(0L, Long.MAX_VALUE);
        values.put("id1", id);
        values.put("id2", id);
        values.put("id3", id);
        values.put("id4", id);
        values.put("id5", id);

        final UUID uuid = new UUID(0L, 0L);

        values.put("uuid1", uuid);
        values.put("uuid2", uuid);
        values.put("uuid3", uuid);
        values.put("uuid4", uuid);
        values.put("uuid5", uuid);

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss z");
        dateFormat.setTimeZone(TimeZone.getTimeZone("GMT"));
        

        values.put("date1", "'2015-10-01 00:00:00+0000'");
        values.put("date2", "'2015-10-02 00:00:00+0000'");
        values.put("date3", "'2015-10-03 00:00:00+0000'");
        values.put("date4", "'2015-10-04 00:00:00+0000'");
        values.put("date5", "'2015-10-05 00:00:00+0000'");

        scriptExecutor.executeScriptTemplate("EntityWithClusteringColumns/insert_many_rows.cql", values);

        //When
        final Tuple2<List<EntityWithClusteringColumns>, ExecutionInfo> listWithStats = manager
                .dsl()
                .select()
                .allColumns_FromBaseTable()
                .without_WHERE_Clause()
                .withFetchSize(3)
                .getListWithStats();


        //Then
        assertThat(listWithStats._1()).hasSize(3);
        assertThat(listWithStats._2().getPagingState()).isNotNull();
    }

```

Please notice that I used `withFetchSize(3)` instead of `.limit(3)`.  Indeed, when you specify a LIMIT, the returned paging state will **most of the time** be null because Cassandra just returns the amount of rows specified by your limit and there is no reason to provide a paging state to fetch next page (because the limit is reached).

The only scenario when you specify a limit and still get a non-null paging state is when the value of your limit is **greater** than the default paging state, which is **5000**
