### ISSUE TITLE
Handle upper-cased column name specified on @Column

### ISSUE THREAD

**Issue by harjitdotsingh** [doanduyhai/Achilles#257] opened 2016-08-18 17:52 UTC
I have the following Definition 

public class LiveResults implements Serializable {

    @PartitionKey(value = 1)
    UUID id;

    @Column(value = "userdn")
    String userdn;
    @Column(value = "queryid")
    @Index(name = "liveresultsqueryid")
    String queryid;

    @Column(value="doclist")
    @Frozen
    List<CSXDoc> doclist;

}

@UDT(name = "csxdoc")
public class CSXDoc {

    @Column( value= "docID")
    private String docID;

    @Column(value = "source")
    private String source;

    @Column(value = "subject")
    private String subject;

    @Column(value = "acm")
    private String acm;

}

I get an error saying

[ERROR] Nested collections/array type/UDT 'com.deciphernow.stream.analytics.live.model.recommendations.CSXDoc' in 'doclist' of class 'com.deciphernow.stream.analytics.live.model.recommendations.LiveResults' should be annotated with @Frozen
[ERROR] Error while parsing: Nested collections/array type/UDT 'com.deciphernow.stream.analytics.live.model.recommendations.CSXDoc' in 'doclist' of class 'com.deciphernow.stream.analytics.live.model.recommendations.LiveResults' should be annotated with @Frozen

even though it has been annotated with Frozen

**Comment by doanduyhai** [comment] 2016-08-18 18:04
You don't get it, the `@Frozen` annotation should be set on `CSXDoc`, not on `List<CSXDoc>`:

```java

@Column(value="doclist")
List<@Frozen CSXDoc> doclist;
```

**Comment by harjitdotsingh** [comment] 2016-08-18 18:10
Thanks. I was trying to look for an example and couldn't see. The only example which I came across was that Frozen being defined on the UDT.

**Comment by doanduyhai** [comment] 2016-08-18 18:18
Closing since it's not an issue

**Comment by harjitdotsingh** [comment] 2016-08-18 18:21
Now its past compilation but when I run this code


ManagerFactory managerFactory = ManagerFactoryBuilder
                .builder(cassClient.get())
                .withDefaultKeyspaceName(colModule.getInstance(CollectionConfig.class).getDatabaseName())
                .doForceSchemaCreation(true).build();


I get this error


info.archinnov.achilles.exception.AchillesException: The keyspace name for the UDT type 'com.deciphernow.stream.analytics.live.model.recommendations.CSXDoc' should be either provided by the 'UDT' annotation or at runtime



I'm not annotating UDT with any keyspace because I'm using different keyspace in test and production. Hence I should use the one which I'm setting as default. So why I keep getting this error ?

**Comment by doanduyhai** [comment] 2016-08-18 18:26
Try to do a complete rebuild to *re-generate* the source code (hint `mvn clean compile`)

**Comment by harjitdotsingh** [comment] 2016-08-18 18:48
I did that. Same issuse,

Its failing at this line


        Optional keyspaceName = Optional.ofNullable(this.staticKeyspace.orElse(this.keyspace));
        Validator.validateTrue(keyspaceName.isPresent(), "The keyspace name for the UDT type \'%s\' should be either provided by the \'%s\' annotation or at runtime", new Object[]{this.udtClass.getCanonicalName(), UDT.class.getSimpleName()});


keyspacename is null. when I do look in the debugger,

**Comment by harjitdotsingh** [comment] 2016-08-18 18:49
Also Getting this error whe validating Schema

@Table(table = "LiveQueryResults")
public class LiveQueryResults implements Serializable {

    @PartitionKey
    UUID id;

    @Column(value = "userdn")
    String userdn;
    @Column(value = "queryid")
    String queryid;


    @Column(value="doclist")
    List<@Frozen CSXDoc> doclist;


    public LiveQueryResults() {
    }

    public UUID getId() {
        return id;
    }

    public String getUserdn() {
        return userdn;
    }

    public String getQueryid() {
        return queryid;
    }


    public void setId(UUID id) {
        this.id = id;
    }

    public void setUserdn(String userdn) {
        this.userdn = userdn;
    }

    public void setQueryid(String queryid) {
        this.queryid = queryid;
    }


    public List<CSXDoc> getDoclist() {
        return doclist;
    }

    public void setDoclist(List<CSXDoc> doclist) {
        this.doclist = doclist;
    }
}

info.archinnov.achilles.exception.AchillesBeanMappingException: Data type 'list<frozen<livetest.csxdoc>>' for column 'doclist' of entity 'class com.deciphernow.stream.analytics.live.model.recommendations.LiveQueryResults' does not match type in live schema 'list<frozen<livetest.csxdoc>>'

	at info.archinnov.achilles.validation.Validator.validateBeanMappingTrue(Validator.java:125)
	at info.archinnov.achilles.internals.schema.SchemaValidator.validateColumns(SchemaValidator.java:69)
	at info.archinnov.achilles.internals.metamodel.AbstractEntityProperty.validateSchema(AbstractEntityProperty.java:342)
	at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.lambda$validateSchema$449(AbstractManagerFactory.java:155)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.validateSchema(AbstractManagerFactory.java:155)
	at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.bootstrap(AbstractManagerFactory.java:118)
	at info.archinnov.achilles.generated.ManagerFactory.<init>(ManagerFactory.java:117)
	at info.archinnov.achilles.generated.ManagerFactoryBuilder.build(ManagerFactoryBuilder.java:38)

**Comment by doanduyhai** [comment] 2016-08-19 05:57
For the null keyspaceName issue, I have an unit test and it works:

```java

   final ManagerFactory managerFactory = ManagerFactoryBuilder
                .builder(cluster)
                .withManagedEntityClasses(EntityWithNestedUDT.class)
                .doForceSchemaCreation(true)
                .withDefaultKeyspaceName(DEFAULT_CASSANDRA_EMBEDDED_KEYSPACE_NAME)
                .build();

        final EntityWithNestedUDT_Manager manager = managerFactory.forEntityWithNestedUDT();

```

```java

@Table(table = "table_with_nested_udt")
public class EntityWithNestedUDT {

    @PartitionKey
    private Long id;

    @Frozen
    @Column
    private UDTWithNoKeyspace udt;

    @Frozen
    @Column
    private UDTWithNestedUDT complexUDT;

    @Column
    private List<@Frozen UDTWithNoKeyspace> listUdt;

...
```

```java

@UDT(name = "no_ks")
public class UDTWithNoKeyspace {

    @Column
    private Long id;

    @Column
    private String value;
...
```

**Comment by harjitdotsingh** [comment] 2016-08-19 13:48
I think it may be some of the jar which may be conflicting. Can you think
of any jar which can cause conflicts  ?

- Harjit

**Comment by harjitdotsingh** [comment] 2016-08-19 14:24
I'm getting this error, have tried different ways but it doesn't make any
sense. Here is the error


info.archinnov.achilles.exception.AchillesBeanMappingException: Data type
'frozen<livetest.csxcontainer>' for column 'csxmetacontainer' of entity
'class recommendations.LiveResults' does not match type in live schema
'frozen<livetest.csxcontainer>'

at
info.archinnov.achilles.validation.Validator.validateBeanMappingTrue(Validator.java:125)
at
info.archinnov.achilles.internals.schema.SchemaValidator.validateColumns(SchemaValidator.java:69)
at
info.archinnov.achilles.internals.metamodel.AbstractEntityProperty.validateSchema(AbstractEntityProperty.java:342)
at
info.archinnov.achilles.internals.runtime.AbstractManagerFactory.lambda$validateSchema$449(AbstractManagerFactory.java:155)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at
java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
at
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at
info.archinnov.achilles.internals.runtime.AbstractManagerFactory.validateSchema(AbstractManagerFactory.java:155)
at
info.archinnov.achilles.internals.runtime.AbstractManagerFactory.bootstrap(AbstractManagerFactory.java:118)
at
info.archinnov.achilles.generated.ManagerFactory.<init>(ManagerFactory.java:54)
at
info.archinnov.achilles.generated.ManagerFactoryBuilder.build(ManagerFactoryBuilder.java:38)
at CSXLiveResultsTest.testCRUD(CSXLiveResultsTest.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at
com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
at
com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
at
com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)




I have attached the project. See if you can figure it out. You will have to
run cassandra locally. I'm running a cassandra docker image. I'm
consistently seeing it.

Thanks,

Harjit

**Comment by doanduyhai** [comment] 2016-08-19 17:48
Just upload your source code somewhere so I can see it

**Comment by harjitdotsingh** [comment] 2016-08-19 18:01
Sent it in a zip file....


- Harjit

**Comment by doanduyhai** [comment] 2016-08-19 18:52
Sent it to doanduyhai@gmail.com

**Comment by doanduyhai** [comment] 2016-08-21 19:34
Ok I can successfully reproduce the issue, it is very subtle.

When we compare the runtimeUDTType vs the statically compiled UDT type created by **Achilles**, the comparison fails here:

```java
public class SchemaValidator {
...

  public static <T> void validateColumns(...) {
     ...
     validateBeanMappingTrue(runtimeType.equals(staticType),"Data type '%s' for column '%s' of entity '%s' does not match type in live schema '%s'",staticType, cqlColumn, entityClass, runtimeType);
     ...
  }
}
```

The reason is that **Achilles** creates the following UDT type:

```sql
CREATE TYPE IF NOT EXISTS livetest.csxdoc(
		docID text,
		source text,
		subject text,
		acm text);
```

But at runtime, since the default naming in Cassandra is **lowercase**, we are comparing `docID` field generated by **Achilles** versus `docid` field fetched by the driver from live schema, and it does not match.

For now, a simple work-around is to lower-case docid:

```java
    @Column(value = "docid")
    private String docID;

```

The unit test is now running for me

**Closed** 2016-08-25 13:22 UTC
Labels: bug

**Comment by nicebalu** [comment] 2018-01-30 02:50
@AchillesBeanMappingException for the UDT

Caused by: info.archinnov.achilles.exception.AchillesBeanMappingException: Data type 'map<text, frozen<r2d2application.r2d2_udt>>' for column 'mappings' of entity 'class com.walmart.qarth.r2d2.dto.ItemIdR2D2' does not match type in live schema 'map<text, frozen<r2d2application.r2d2_udt>>'

**Comment by nicebalu** [comment] 2018-01-30 02:50
@achillesbeanmappingexception for the UDT

Caused by: info.archinnov.achilles.exception.AchillesBeanMappingException: Data type 'map<text, frozen<r2d2application.r2d2_udt>>' for column 'mappings' of entity 'class com.walmart.qarth.r2d2.dto.ItemIdR2D2' does not match type in live schema 'map<text, frozen<r2d2application.r2d2_udt>>'

![image](https://user-images.githubusercontent.com/19192497/35545717-4f4c0a14-0525-11e8-802b-9454c76df56d.png)

**Comment by nicebalu** [comment] 2018-01-30 02:51
![image](https://user-images.githubusercontent.com/19192497/35545724-59af4ba6-0525-11e8-9dbe-9d9c69f72688.png)

**Comment by doanduyhai** [comment] 2018-01-30 19:15
Achilles version ?
