### ISSUE TITLE
Getting an error when validating when using Collection of UDT

### ISSUE THREAD

**Issue by harjitdotsingh** [doanduyhai/Achilles#258] opened 2016-08-18 19:08 UTC
I have this types

@Table(table = "LiveQueryResults")
public class LiveQueryResults implements Serializable {

    @PartitionKey
    UUID id;

    @Column(value = "userdn")
    String userdn;
    @Column(value = "queryid")
    String queryid;

    @Column(value="doclist")
    List<@Frozen CSXDoc> doclist;

}

package com.deciphernow.stream.analytics.live.model.recommendations;

import info.archinnov.achilles.annotations.Column;
import info.archinnov.achilles.annotations.UDT;

import java.util.Objects;

/**
 * Created by harjitsingh on 8/18/16.
 */

@UDT(keyspace = "",name = "csxdoc")
public class CSXDoc {

    @Column( value= "docID")
    private String docID;

    @Column(value = "source")
    private String source;

    @Column(value = "subject")
    private String subject;

    @Column(value = "acm")
    private String acm;

    public String getDocID() {
        return docID;
    }

    public void setDocID(String docID) {
        this.docID = docID;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CSXDoc csxDoc = (CSXDoc) o;
        return Objects.equals(docID, csxDoc.docID);
    }

    @Override
    public int hashCode() {
        return Objects.hash(docID, source, subject);
    }

    public String getAcm() {
        return acm;
    }

    public void setAcm(String acm) {
        this.acm = acm;
    }
}

I get this error 

info.archinnov.achilles.exception.AchillesBeanMappingException: Data type 'list<frozen<livetest.csxdoc>>' for column 'doclist' of entity 'class com.deciphernow.stream.analytics.live.model.recommendations.LiveQueryResults' does not match type in live schema 'list<frozen<livetest.csxdoc>>'

when executing building the manager factory.

**Comment by doanduyhai** [comment] 2016-08-24 15:49
Closing it since it's a duplicate of #257

**Closed by doanduyhai** 2016-08-24 15:49 UTC
Labels: duplicate
