### ISSUE TITLE
Achilles stops generating source with 5.3.0

### ISSUE THREAD

**Issue by andrewv99** [doanduyhai/Achilles#315] opened 2017-08-30 00:19 UTC
Hi,

Background: I have built and run an application for some time now under 5.2.0, without issue. I have 2 related maven projects - the first contains only Entities, UDTs, and a runtime config class. The second (dependent on the first) uses those entities for providing cassandra DB services (as an aside, I find this makes the IDE / maven use simpler, because there are no issues with having generated source used in the same project as it is built).

I tried rebuilding from scratch with 5.3.0, and although I get no errors when I am compiling the entities, there is no generated source. I compiled under maven with the -X flag, and there are no new warnings, etc. I then tried 5.2.1, and it worked as well as 5.2.0. I have created a sample Entity and config that reproduce the error under 5.3.0 (but both generate code in 5.2.0 and 5.2.1).

Environment:

Kubuntu 14.04.5, 64 Bit
Oracle JDK 1.8.0_112

I am building in a short path directory, so it is not a path length issue.

I looked through the change log, but could not see anything in terms of any required change I might need to make to upgrade to 5.3.0.

Thanks for any pointers on what I need to do to fix this.

Sample Code:

**sample/CassAchillesEntityCompileTimeConfig.java**

package sample;

import info.archinnov.achilles.annotations.CompileTimeConfig;
import info.archinnov.achilles.type.CassandraVersion;

@CompileTimeConfig(cassandraVersion = CassandraVersion.CASSANDRA_3_7, projectName = "sample_prj")
public class CassAchillesEntityCompileTimeConfig
{
}

**sample/SampleEntity.java**

package sample;

import java.io.Serializable;
import java.util.Map;

import info.archinnov.achilles.annotations.ClusteringColumn;
import info.archinnov.achilles.annotations.Column;
import info.archinnov.achilles.annotations.PartitionKey;
import info.archinnov.achilles.annotations.Table;

@Table(table = SampleEntity.TABLE_NAME, keyspace = SampleEntity.KEYSPACE)
public class SampleEntity implements Serializable
{
	public static final String KEYSPACE = "analysis";

	public static final String TABLE_NAME = "sample_entity";

	private static final long serialVersionUID = 1L;

	@PartitionKey(value = 1)
	@Column(value = "dsp")
	private String data;

	@PartitionKey(value = 2)
	@Column(value = "id")
	private String id;

	@Column(value = "sv")
	@ClusteringColumn(value = 1)
	private int schemaVersion;

	@Column(value = "name")
	private String name;

	@Column(value = "clm")
	private Map<String, Long> clMap;

	@Column(value = "jd")
	private String jData;

	public SampleEntity()
	{
	}

	public String getData()
	{
		return data;
	}

	public void setData(final String data)
	{
		this.data = data;
	}

	public String getId()
	{
		return id;
	}

	public void setId(final String id)
	{
		this.id = id;
	}

	public int getSchemaVersion()
	{
		return schemaVersion;
	}

	public void setSchemaVersion(final int schemaVersion)
	{
		this.schemaVersion = schemaVersion;
	}

	public String getName()
	{
		return name;
	}

	public void setName(final String name)
	{
		this.name = name;
	}

	public Map<String, Long> getClMap()
	{
		return clMap;
	}

	public void setClMap(final Map<String, Long> clMap)
	{
		this.clMap = clMap;
	}

	public String getJData()
	{
		return jData;
	}

	public void setJData(final String jData)
	{
		this.jData = jData;
	}

}

**Comment by vrudikov** [comment] 2017-08-30 20:03
@andrewv99 Yeah. Have the same issue. I thought that there some incompatibility with net.ltgt.apt Gradle plugin, but no it's 5.3.0 issue

@doanduyhai Any thoughts?

**Comment by sweetacaro** [comment] 2017-09-01 03:23
same problem for me. Looks like Achilles5.3 does not generate the ManagerFactory...

**Comment by vrudikov** [comment] 2017-09-01 07:18
It's doesn't trigger AchillesProcessor at all

**Comment by CrWEE** [comment] 2017-09-01 08:34
Same here :/

**Comment by doanduyhai** [comment] 2017-09-01 09:21
Ok let me reproduce it and shoot a fix

**Comment by doanduyhai** [comment] 2017-09-01 09:45
OK found the issue. For some reason, Google Auto Services library did **not** generate `META-INF/services/javax.annotation.processing.Processor` file for **`achilles-core.5.3.0`**

**Comment by vrudikov** [comment] 2017-09-01 09:48
Can you explain how it works? i mean. Are there some GAS deps included with Achilles or what?

**Comment by doanduyhai** [comment] 2017-09-01 09:55
Google Auto Services will generate file `META-INF/services/javax.annotation.processing.Processor` in **`achilles-core-5.3.0.jar`**

The content of the file is:

info.archinnov.achilles.internals.apt.processors.meta.AchillesProcessor

**Comment by doanduyhai** [comment] 2017-09-01 09:56
Ok found the culprit, I accidentally de-activated the `maven-processor-plugin` important plugin in this commit: https://github.com/doanduyhai/Achilles/commit/3617e88c555e8a56e29523729d142d60a0c733b1#diff-bcf0077ef13c08e33d73ee7404888313L134

**Comment by doanduyhai** [comment] 2017-09-01 09:57
I'm going to do a release 5.3.1 with the fix soon

**Comment by vrudikov** [comment] 2017-09-01 11:07
@doanduyhai Can you leave here a note when it's get released in Maven central, plz. Thank you

**Comment by andrewv99** [comment] 2017-09-01 11:15
@doanduyhai  Thanks for investigating this issue and targeting a new release. I will retest my application build/run after you have made the release and advise my retest results.

**Comment by doanduyhai** [comment] 2017-09-01 11:49
**Achilles 5.3.1** is released. The jar will be available in a few hours on Maven Central

**Comment by vrudikov** [comment] 2017-09-01 11:54
@doanduyhai Awesome and blazing fast work! Thank you

**Comment by vrudikov** [comment] 2017-09-01 12:14
@doanduyhai Off-topic: is new GROUP BY feature allows to collect results to specific class? Kinda mapping on the fly

**Comment by doanduyhai** [comment] 2017-09-01 12:18
@vrudikov No, with `GROUP BY` you may want to retrieve the data as a `List<TypedMap>` since the aggregated column(s) are not mapped to any field of your entity

**Comment by doanduyhai** [comment] 2017-09-01 12:29
Thanks all for raising the issue quickly. The artifact achilles-core 5.3.1 is now **available** on Maven Central: http://search.maven.org/#artifactdetails%7Cinfo.archinnov%7Cachilles-core%7C5.3.1%7Cjar

**Closed** 2017-09-01 12:29 UTC
Labels: bug

**Comment by andrewv99** [comment] 2017-09-01 14:26
Retested with 5.3.1. I can confirm the issue is resolved for me and runtime works fine too. Thanks.

**Comment by vrudikov** [comment] 2017-09-01 15:23
> Retested with 5.3.1. I can confirm the issue is resolved for me and runtime works fine too. Thanks.
Did the same. Confirm - works as designed
